# version: '3.8'

# services:
#   telegram-bot-api:
#     image: aiogram/telegram-bot-api:latest
#     container_name: tg_api_local
#     environment:
#       TELEGRAM_API_ID: ${API_ID}
#       TELEGRAM_API_HASH: ${API_HASH}
#       TELEGRAM_LOCAL: "1"
#     volumes:
#       - ./tg_data:/var/lib/telegram-bot-api
#     ports:
#       - "8081:8081"
#     restart: always

#   hifi-bot:
#     build: .
#     container_name: hifi_bot_app
#     depends_on:
#       - telegram-bot-api
#     environment:
#       - BOT_TOKEN=${BOT_TOKEN}
#       - API_URL=http://telegram-bot-api:8081/bot
#       - QOBUZ_TOKEN=${QOBUZ_TOKEN}
#     volumes:
#       - ./downloads:/app/downloads
#     restart: always
